# Generated by Django 4.1 on 2022-08-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='new event', max_length=40),
            preserve_default=False,
        ),
    ]
