# Generated by Django 4.1 on 2022-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0002_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', through='undergroundapi.EvtArtist', to='undergroundapi.artist'),
        ),
    ]
