# Generated by Django 4.1 on 2022-08-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0004_alter_chosenshow_user_alter_event_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
