# Generated by Django 4.1 on 2022-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0005_alter_event_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
