# Generated by Django 4.1 on 2022-09-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0006_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='social',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
