# Generated by Django 4.1.1 on 2022-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergroundapi', '0007_alter_artist_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
